In [1]:
import numpy as np
import sympy as sp

In [2]:
#Q2.
np.random.seed(45)
A=np.random.randint(0,10,(5,5))
A

array([[3, 0, 5, 3, 4],
       [9, 8, 1, 5, 9],
       [6, 8, 7, 8, 5],
       [2, 8, 1, 6, 4],
       [8, 4, 6, 4, 9]])

In [3]:
A=np.array([[3, 0, 5, 3, 4],[9, 8, 1, 5, 9],[6, 8, 7, 8, 5],[2, 8, 1, 6, 4],[8, 4, 6, 4, 9]])
A[0]=A[0]/3
A

array([[1, 0, 1, 1, 1],
       [9, 8, 1, 5, 9],
       [6, 8, 7, 8, 5],
       [2, 8, 1, 6, 4],
       [8, 4, 6, 4, 9]])

In [4]:
A[1]=A[1]-9*A[0]
A[2]=A[2]-6*A[0]
A[3]=A[3]-2*A[0]
A[4]=A[4]-8*A[0]
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  8, -8, -4,  0],
       [ 0,  8,  1,  2, -1],
       [ 0,  8, -1,  4,  2],
       [ 0,  4, -2, -4,  1]])

In [5]:
A[1]=A[1]/8
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  8,  1,  2, -1],
       [ 0,  8, -1,  4,  2],
       [ 0,  4, -2, -4,  1]])

In [6]:
A[2]=A[2]-8*A[1]
A[3]=A[3]-8*A[1]
A[4]=A[4]-4*A[1]
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  0,  9,  2, -1],
       [ 0,  0,  7,  4,  2],
       [ 0,  0,  2, -4,  1]])

In [7]:
A[2]=A[2]/9
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  7,  4,  2],
       [ 0,  0,  2, -4,  1]])

In [8]:
A[3]=A[3]-7*A[2]
A[4]=A[4]-2*A[2]
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  4,  2],
       [ 0,  0,  0, -4,  1]])

In [9]:
A[3]=A[3]/4
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0, -4,  1]])

In [10]:
A[4]=A[4]+4*A[3]
A

array([[ 1,  0,  1,  1,  1],
       [ 0,  1, -1,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1]])